version: 2.1

jobs:
  lint_and_test:
    docker:
      - image: circleci/node:12.4.0
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test
  publish:
    docker:
      - image: circleci/node:12.4.0
    steps:
      - checkout
      - run:
          name: Authenticate with NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Install
          command: npm install
      - run:
          name: Publish to NPM
          command: |
            set -e

            NAME=$(node -p "require('./package.json').name")
            VERSION=$(node -p "require('./package.json').version")
            PUBLISHED_VERSION=$(npm view $NAME version)

            if [ "$VERSION" != "$PUBLISHED_VERSION" ]
            then
              npm publish
            fi

workflows:
  version: 2
  commit-workflow:
    jobs:
      - lint_and_test
      - publish:
          requires:
            - lint_and_test
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
