version: 2.1

jobs:
  lint_and_test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Authenticate with NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Install
          command: npm i --force
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm test -- --runInBand --collectCoverage false
  publish:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Publish to NPM
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            echo ".publish/publish.sh" >> .npmignore
            git clone https://github.com/modernpoacher/publish.git .publish
            .publish/publish.sh

workflows:
  commit-workflow:
    jobs:
      - lint_and_test:
          filters:
            branches:
              only: main
      - publish:
          requires:
            - lint_and_test
          filters:
            tags:
              only: /^v.*/
