'use strict';Object.defineProperty(exports,"__esModule",{value:true});var _createClass=function(){function defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||false;descriptor.configurable=true;if("value"in descriptor)descriptor.writable=true;Object.defineProperty(target,descriptor.key,descriptor);}}return function(Constructor,protoProps,staticProps){if(protoProps)defineProperties(Constructor.prototype,protoProps);if(staticProps)defineProperties(Constructor,staticProps);return Constructor;};}();var _react=require('react');var _react2=_interopRequireDefault(_react);var _propTypes=require('prop-types');var _propTypes2=_interopRequireDefault(_propTypes);var _immutable=require('immutable');var _immutable2=_interopRequireDefault(_immutable);var _shinkansenRails=require('shinkansen-rails');var _reverse=require('./reverse');var _reverse2=_interopRequireDefault(_reverse);var _forward=require('./forward');var _forward2=_interopRequireDefault(_forward);function _interopRequireDefault(obj){return obj&&obj.__esModule?obj:{default:obj};}function _objectWithoutProperties(obj,keys){var target={};for(var i in obj){if(keys.indexOf(i)>=0)continue;if(!Object.prototype.hasOwnProperty.call(obj,i))continue;target[i]=obj[i];}return target;}function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError("Cannot call a class as a function");}}function _possibleConstructorReturn(self,call){if(!self){throw new ReferenceError("this hasn't been initialised - super() hasn't been called");}return call&&(typeof call==="object"||typeof call==="function")?call:self;}function _inherits(subClass,superClass){if(typeof superClass!=="function"&&superClass!==null){throw new TypeError("Super expression must either be null or a function, not "+typeof superClass);}subClass.prototype=Object.create(superClass&&superClass.prototype,{constructor:{value:subClass,enumerable:false,writable:true,configurable:true}});if(superClass)Object.setPrototypeOf?Object.setPrototypeOf(subClass,superClass):subClass.__proto__=superClass;}var Gears=function(_React$Component){_inherits(Gears,_React$Component);function Gears(){var _ref;var _temp,_this,_ret;_classCallCheck(this,Gears);for(var _len=arguments.length,args=Array(_len),_key=0;_key<_len;_key++){args[_key]=arguments[_key];}return _ret=(_temp=(_this=_possibleConstructorReturn(this,(_ref=Gears.__proto__||Object.getPrototypeOf(Gears)).call.apply(_ref,[this].concat(args))),_this),_this.state={},_temp),_possibleConstructorReturn(_this,_ret);}_createClass(Gears,[{key:'componentWillReceiveProps',// define state
/**
   *  Convert latest 'props' to an Immutable.Map() and store in 'state'
   *
   *  @param {Object} props   Latest props
   */value:function componentWillReceiveProps(_ref2){var reverse=_ref2.reverse,forward=_ref2.forward;// console.log('(Gears)componentWillReceiveProps()', { reverse, forward }) // eslint-disable-line
this.setState({REVERSE:_immutable2.default.Map(reverse),FORWARD:_immutable2.default.Map(forward)});}/**
   *  Compare latest 'props' with previous 'state' for changes to 'reverse' or 'forward'
   *
   *  @param {Object} props   Latest props
   */},{key:'shouldComponentUpdate',value:function shouldComponentUpdate(_ref3){var pattern=_ref3.pattern,props=_objectWithoutProperties(_ref3,['pattern']);// console.log('(Gears)shouldComponentUpdate()', { pattern, ...props })
var PATTERN=this.props.pattern;if(pattern!==PATTERN)return true;var reverse=props.reverse,forward=props.forward;var _state=this.state,REVERSE=_state.REVERSE,FORWARD=_state.FORWARD;// state must be defined
/**
     *  Compare object values
     */return!_immutable2.default.is(_immutable2.default.Map(reverse),REVERSE)||!_immutable2.default.is(_immutable2.default.Map(forward),FORWARD);}},{key:'render',value:function render(){// console.log('(Gears)render()')
var _props=this.props,reverse=_props.reverse,forward=_props.forward,pattern=_props.pattern;var reverseGear=_shinkansenRails.Rails.engage(reverse,pattern)?_react2.default.createElement(_reverse2.default,{pathname:_shinkansenRails.Rails.path(reverse,pattern)}):null;var forwardGear=_shinkansenRails.Rails.engage(forward,pattern)?_react2.default.createElement(_forward2.default,{pathname:_shinkansenRails.Rails.path(forward,pattern)}):null;if(reverseGear||forwardGear){return _react2.default.createElement('ul',{className:'shinkansen-gears',key:'shinkansen-gears'},reverseGear,forwardGear);}return null;}}]);return Gears;}(_react2.default.Component);exports.default=Gears;Gears.defaultProps={pattern:_shinkansenRails.Rails.pattern()};Gears.propTypes={reverse:_propTypes2.default.object,forward:_propTypes2.default.object,pattern:_propTypes2.default.string};