#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

get_package_version_changes () {
  git diff HEAD~1..HEAD~0 -- "origin/$CURRENT_BRANCH" package.json | grep -e '+\s*\"version\":\s\".*"'
}

has_package_version_changes () {
  [ ! -z "$(get_package_version_changes)" ]
}

get_package_changes () {
  git diff HEAD~1..HEAD~0 -- "origin/$CURRENT_BRANCH" package.json
}

has_package_changes () {
  [ ! -z "$(get_package_changes)" ]
}

if ! has_package_version_changes;
then
  if has_package_changes;
  then
    npx cross-env DEBUG=@modernpoacher/hooks* node .husky/post-commit.mjs
  fi
fi
